@forward-modifiers Shift Control

Alt >> Meta
Meta >> Alt

[stage]

[class != "com.mitchellh.ghostty"]

Meta{ArrowLeft} >> Home # Move cursor to start of line
Meta{ArrowRight} >> End # Move cursor to end of line
Meta{ArrowUp} >> Control{Home} # Move cursor to start of input
Meta{ArrowDown} >> Control{End} # Move cursor to end of input

(Meta Shift){ArrowLeft} >> Shift{Home} # Select to start of line
(Meta Shift){ArrowRight} >> Shift{End} # Select to end of line
(Meta Shift){ArrowUp} >> (Shift Control){Home} # Select to start of input
(Meta Shift){ArrowDown} >> (Shift Control){End} # Select to end of input

Alt{ArrowLeft} >> Control{ArrowLeft} # Move cursor left by word
Alt{ArrowRight} >> Control{ArrowRight} # Move cursor right by word
(Alt Shift){ArrowLeft} >> (Control Shift){ArrowLeft} # Select left by word
(Alt Shift){ArrowRight} >> (Control Shift){ArrowRight} # Select right by word

Alt{Backspace} >> Control{Backspace} # Delete word backward
Alt{Delete} >> Control{Delete} # Delete word forward

(Alt Meta){ArrowUp} >> (Alt Control){ArrowUp} # Add cursor above
(Alt Meta){ArrowDown} >> (Alt Control){ArrowDown} # Add cursor below

[class != /^com.mitchellh.ghostty|code$/]

Meta{Backspace} >> Shift{Home} Delete
Meta{Delete} >> Shift{End} Delete

[class = "com.mitchellh.ghostty"]

# Just map Meta to Ctrl and handle further mapping in config
Meta{ArrowUp} >> Control{ArrowUp}
Meta{ArrowDown} >> Control{ArrowDown}
Meta{ArrowLeft} >> Control{ArrowLeft}
Meta{ArrowRight} >> Control{ArrowRight}
Meta{Backspace} >> Control{Backspace}
Meta{Delete} >> Control{Delete}

[class = "code"]

# Move editor shortcut
(Control Meta){ArrowLeft} >> (Control Alt){ArrowLeft}
(Control Meta){ArrowRight} >> (Control Alt){ArrowRight}

# Workaround for line deletion shortcuts
#
# In VS Code, cursor movement within editor inputs can be fully remapped from
# any keystroke, but other inputs (quick picks, search widgets, file pickers)
# cannot be remapped. To implement line deletion in Windows, multiple keystrokes
# are required, which works fine for inputs (editor or otherwise) but doesn't
# map cleanly to terminal keybindings.
#
# Because of this, we make the choice to sacrifice line deletion keybindings in
# non-editor inputs so we can have line deletion be triggered by a single
# keystroke using surrogate keys, which can then be handled in VS Code
# keybindings for the editor and terminal.
Meta{Backspace} >> Control{F13}
Meta{Delete} >> Control{F14}

# Workaround for smart select shortcuts
#
# The physical keys used for these shortcuts map to the keystrokes sent for
# selecting by word.
(Control Shift){ArrowLeft} >> Control{F15}
(Control Shift){ArrowRight} >> Control{F16}

# Workaround for triggering command palette in terminal
#
# This conflicts with my shortcut for printing the active file path to the
# terminal.
(Meta Shift){P} >> Control{F19}

[class = /^com.mitchellh.ghostty|code$/]

# Workaround for copy/paste/search in terminal
Control{C} >> (Control Alt){C}
Control{V} >> (Control Alt){V}
Control{F} >> (Control Alt){F}

[default]

# Map Meta to Control for shortcuts
apply[ \
  Meta{$0} >> Control{$0}; \
  (Meta Shift){$0} >> (Control Shift){$0}; \
  (Meta Alt){$0} >> (Control Alt){$0}; \
  (Meta Shift Alt){$0} >> (Control Shift Alt){$0}, \
  A, B, C, D, E, F, G, H, I, J, K, L, M, \
  N, O, P, Q, R, S, T, U, V, W, X, Y, Z, \
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, \
  Backquote, Minus, Equal, BracketLeft, BracketRight, Backslash, Semicolon, Quote, Comma, Period, Slash, Enter]

# Disable Alt press behavior
Alt{Any} >> Alt{Any}
Alt >>
