#!/usr/bin/env fish

argparse --ignore-unknown "s/status-options=" -- $argv
set args $argv

function list_function -V args
    set sep \u001f
    git worktree list --porcelain $args | string join $sep | string split $sep$sep | string match "*"$sep"HEAD*" | string match -g -r "^worktree (.*?)$sep"
end

source (status dirname)/git_interactive_command.fish \
    --fzf-flag=--ansi \
    --fzf-flag=--multi \
    --fzf-flag=--scheme=path \
    --main-view-name=worktrees \
    --items-variable=worktrees \
    --no-items-message="No worktree selected." \
    --list-function=list_function \
    --items-command=cat \
    --view-command="git -C \$items -c color.status=always status $_flag_status_options"
