#!/usr/bin/env fish

if not set -q argv[1]
    echo "fatal: must supply revision" >&2
    exit 1
end

set revision $argv[1]
set -x DELTA_PAGER less --jump-target=.5 --pattern=TODO

git diff --unified=0 $revision...
