#!/usr/bin/env fish

argparse --ignore-unknown "s/show-options=" -- $argv

set args (string escape -- $argv)

source (status dirname)/git_fzf_command.fish \
    --flags --multi \
    --main-view-name stashes \
    --items-variable stashes \
    --no-items-message "No stash selected." \
    --list-command "git stash list $args" \
    --items-command "cut -d ':' -f 1" \
    --view-command "git show --color --diff-merges=first-parent $_flag_stash_show_options \\\$items"
