#!/usr/bin/env fish

argparse --ignore-unknown "p/path=" -- $argv

set args (string escape -- $argv)

if set -q _flag_path
    set path -- $_flag_path
end

source (status dirname)/git_fzf_command.fish \
    --flags "--ansi --multi" \
    --header (git show --format="" --shortstat $args $path) \
    --list-command "git show --format="" --name-status $args $path | format_git_name_status" \
    --item-command "cut -d ' ' -f 2,4" \
    --view-command "xargs git -C (git rev-parse --show-toplevel) show --format="" $args --" \
    --summary-command "git show --no-patch $args $path"
