#!/usr/bin/env fish

argparse "c/create-branch=" -- $argv

if not set -q argv[1]
    echo "fatal: must supply base revision" >&2
    exit 1
end

set base_revision $argv[1]
set current_branch (git branch --show-current)

git commit

set commit (git rev-parse HEAD)

if not test -z (git status --porcelain | string collect)
    set should_stash
end

if set -q should_stash
    git stash --include-untracked
end

git reset --hard HEAD~

if set -q _flag_create_branch
    git switch -c $_flag_create_branch $base_revision
else
    git switch $base_revision
end

git cherry-pick $commit
git switch $current_branch

if set -q should_stash
    git stash pop --index
end
