#!/usr/bin/env fish

argparse --ignore-unknown "o/stash-show-options=" -- $argv

source (status dirname)/git_fzf_command.fish \
    --flags --multi \
    --list-command "git stash list $argv" \
    --item-command "cut -d ':' -f 1" \
    --view-command "xargs -I [] git stash show --patch $_flag_stash_show_options []"
