#!/usr/bin/env fish

argparse --ignore-unknown "g/graph-options=" -- $argv

set args (string escape -- $argv)

source (status dirname)/git_fzf_command.fish \
    --flags "--ansi --multi" \
    --main-view-name branches \
    --items-variable branches \
    --no-items-message "No branch selected." \
    --list-command "git branch --color $args" \
    --items-command "sed -e 's/*//' -e 's/+//' -e 's/->//' | string split --no-empty ' '" \
    --view-command "git graph --color $_flag_graph_options \\\$items"
