#!/usr/bin/env fish

source (status dirname)/git_interactive_command.fish

argparse --ignore-unknown "s/show-options=" -- $argv
set args $argv

function list_function -V args
    git stash list $args
end

set -a DELTA_FEATURES navigate-files

git_interactive_command \
    --fzf-flag=--multi \
    --main-view-name=stashes \
    --items-variable=stashes \
    --no-items-message="No stash selected." \
    --hyperlink-format="vscode://jaminthorns.gitsquatch/\$items:{path}:{line}" \
    --list-function=list_function \
    --items-command="cut -d : -f 1" \
    --view-command="git show --color --decorate --diff-merges=first-parent $_flag_stash_show_options \$items"
