#!/usr/bin/env fish

source (status dirname)/git_interactive_command.fish

argparse --ignore-unknown "s/status-options=" -- $argv
set args $argv

function list_function -V args
    git worktree list --porcelain $args | string join $SEP | string split $SEP$SEP | string match "*"$SEP"HEAD*" | string match -g -r "^worktree (.*?)$SEP"
end

git_interactive_command \
    --fzf-flag=--ansi \
    --fzf-flag=--multi \
    --fzf-flag=--scheme=path \
    --main-view-name=worktrees \
    --items-variable=worktrees \
    --no-items-message="No worktree selected." \
    --list-function=list_function \
    --items-command=cat \
    --view-command="git -C \$items -c color.status=always status $_flag_status_options"
