fish -c "tide configure --auto \
  --style='Classic' \
  --prompt_colors='16 colors' \
  --show_time='No' \
  --classic_prompt_separators='Slanted' \
  --powerline_prompt_heads='Slanted' \
  --powerline_prompt_tails='Slanted' \
  --powerline_prompt_style='One line' \
  --prompt_spacing='Compact' \
  --icons='Few icons' \
  --transient='No'" > /dev/null
