[skin]
default = "ansi(7) none"
tree = "gray(10) none / gray(6) none"
file = "none none"
directory = "ansi(4) none bold"
exe = "ansi(2) none bold"
link = "ansi(6) none"
perm__ = "gray(10) none / gray(6) none"
perm_r = "ansi(3) none"
perm_w = "ansi(1) none"
perm_x = "ansi(2) none"
owner = "ansi(3) none"
group = "ansi(3) none"
count = "ansi(4) none"
dates = "ansi(8) none"
git_branch = "ansi(3) none"
git_insertions = "ansi(2) none"
git_deletions = "ansi(1) none"
git_status_current = "none none"
git_status_modified = "ansi(3) none"
git_status_new = "ansi(2) none"
git_status_ignored = "ansi(8) none"
git_status_conflicted = "ansi(1) none"
git_status_other = "ansi(6) none"
char_match = "ansi(6) none"
file_error = "ansi(1) none"
flag_label = "ansi(8) none"
flag_value = "ansi(3) none bold"
input = "none none"
status_error = "ansi(15) ansi(1)"
status_job = "ansi(5) ansi(0)"
status_normal = "none ansi(0)"
status_italic = "ansi(4) ansi(0) italic"
status_bold = "ansi(6) ansi(0) bold"
status_code = "ansi(3) ansi(0)"
status_ellipsis = "none ansi(0)"
help_paragraph = "none none"
help_bold = "ansi(6) none bold"
help_italic = "ansi(4) none italic"
help_code = "ansi(3) none"
help_headers = "none none"
preview_title = "none ansi(0)"
preview = "none ansi(0)"
preview_line_number = "ansi(8) none"
preview_match = "none ansi(2)"
hex_null = "ansi(8) none"
hex_ascii_graphic = "none none"
hex_ascii_whitespace = "ansi(2) none"
hex_ascii_other = "ansi(3) none"
hex_non_ascii = "ansi(1) none"
staging_area_title = "none ansi(0)"
mode_command_mark = "ansi(0) ansi(6) bold"
